columns = {
    "scans" : [
        "id",               
        "commit_id",           
        "project_id",          
        "db_create_start",     
        "db_create_stop",       
        "scan_start_date",     
        "scan_stop_date",       
        "tool_name" ,           
        "tool_version" ,        
        "tool_query_commit_id",
        "sarif_file_name" ,    
        "results_count" ,      
        "rules_count"  ,       
],
"results" : [
        'id',               
        'scan_id',          
        'query_id',         
        'query_kind',       
        'query_precision',  
        'query_severity',  
        'query_tags',    
        'codeFlow_id',      
        'message'  ,        
        'message_object'  , 
        'location' , 
        
        'source_startLine', 
        'source_startCol',
        'source_endLine' ,  
        'source_endCol' , 
        'sink_startLine' , 
        'sink_startCol',   
        'sink_endLine' ,   
        'sink_endCol' ,
        'source_object' ,  
        'sink_object',
        'source_location',
        'sink_location'   
],
"projects" : [
        "id"     ,            
        "project_name" ,     
        "creation_date",     
        "repo_url" ,          
        "primary_language"  , 
        "languages_analyzed" 
],
"codeflows" : [
"codeflow_id",
"codeflow_index",
"threadflow_index",
"location_index",
"endColumn",
"endLine",
"startColumn",
"startLine",
"artifact_index",
"uri",
"uriBaseId",
"message"
]
}