# -*- mode: org; org-confirm-babel-evaluate: nil; coding: utf-8 -*-
#+OPTIONS: org-confirm-babel-evaluate:nil
#+LANGUAGE:  en
#+TEXT:      
#+OPTIONS: ^:{} H:2 num:t \n:nil @:t ::t |:t ^:nil f:t *:t TeX:t LaTeX:t skip:nil p:nil
#+OPTIONS: toc:nil
#+HTML_HEAD: <link rel="stylesheet" type="text/css" href="./l3style.css"/>
#+HTML: <div id="toc">
#+TOC: headlines 2        insert TOC here, with two headline levels
#+HTML: </div> 
# 
#+HTML: <div id="org-content">

* The notes directory
  This directory is for notes that may be useful, but aren't complete enough to
  serve as documentation in their current state.

  Think of it as staging for [[../docs]].

  Short notes start as sections in this README.  They will be moved if separate
  file make more sense.

** The typegraphs
   The type graph files are derived from a sarif input file, with various options
   controlling output.

   To produce dot maps of a sarif file type graph, from raw (largest) to fully
   filled (most compact):

   #+BEGIN_SRC sh
     cd ../data/treeio/2022-02-25

     # Everything:
     ../../../bin/sarif-to-dot -t -d  results.sarif | dot -Tpdf > typegraph-td.pdf

     # Suppress edges to int/bool/string types in dot graph
     ../../../bin/sarif-to-dot -td -n results.sarif | dot -Tpdf > typegraph-tdn.pdf

     # Additionally, only report unique array entry signatures
     ../../../bin/sarif-to-dot -td -nu results.sarif | dot -Tpdf > typegraph-tdnu.pdf

     # Additionally, fill in missing (optional) entries in sarif input before other steps.
     ../../../bin/sarif-to-dot -td -nuf results.sarif | dot -Tpdf > typegraph-tdnuf.pdf

   #+END_SRC

** The automationDetails.id
   The =automationDetails.id= entry is produced by CodeQL when using the
   =--sarif-category= flag.

   The prerequisites for tracing its flow through the tools is started in
   [[../data/build-multiple-sarifs.sh]]

   #+BEGIN_SRC sh :session shared :results output 
     cd ~/local/sarif-cli/ && ag -l automationDetails |cat
   #+END_SRC

   #+RESULTS:
   : notes/README.org
   : notes/README.html
   : scripts/table-tests.sh
   : sarif_cli/signature_single_CLI.py
   : sarif_cli/table_joins_CLI.py
   : sarif_cli/scan_tables.py
   : sarif_cli/signature.py
   : 
   : [32mhohn@gh-hohn [33m~/local/sarif-cli[0m

#+HTML: </div> 
   
